# example config for usage with the Sonoff Zbridge controller and Home Assistant
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto # your mqtt broker IP / DNS name
serial:
  port: tcp://192.168.3.6:8888 # IP of your Zigbee bridge
  adapter: ezsp
# alternative with USB connection
#serial:  
#  port: /dev/ttyUSB0
frontend: true
advanced:
  network_key: GENERATE # generates a new key on first start and automatically replaces this